# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Embodied Robotics and Automation Lab(ERA) @ USF
email: xlin2@usf.edu
description:  # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://xiaominlin.github.io/" # the base hostname & protocol for your site
twitter_username: XiaominLin11
github_username:  xiaominlin

# Build settings
markdown: kramdown
highlighter: rouge
